Ch setup locally#164005365
VerbenaZ/up-to-date pull request #1
Opened 2019-02-17 13:03 UTC by VerbenaZ

2019-02-17 20:11 UTC, nwashangai requested changes
Good attempt.

2019-02-17 20:11 UTC, nwashangai commented on Level_1.js/SumUp.js
> +const SumUp = [1, 2, 3, 4];
Please I don't want a constant as variable

2019-02-17 20:11 UTC, nwashangai commented on Level_1.js/SumUp.js
> +const sum = SumUp. reduce ((total, value) => total + value, 0);
put this in a function and call the function sumUp, something like this 
```
const sumUp = (arr) => {
return arr.reduce ((total, value) => total + value, 0);
}
```

2019-02-21 13:05 UTC, VerbenaZ commented
i have done the corrections, it no longer sum up to 10, but rather sums varieties of arrays, no matter the numbers imputed and returns the total of the summed arrays.

const SumUp = (okon, akpos) => {
const here = okon + akpos;
return here; 
}
console.log(SumUp (5, 15));

2019-02-21 13:06 UTC, closed without merging